name : Python APP CI

on :
    push :
        branches:
            - master
    pull_request:
        branches : 
            - master

jobs : 
    app_test:
        runs_on: ubuntu-latest

        steps:
            # step 1: check out the code from respository
            - name: checkout code
              uses: actions/checkout@v2

            # step 2: set up python environment
            - name : setup python environment
              uses: actions/setup-python@v2
              with:
                    python-version: '3.8' # specify the python version you want to use

            # step 3 : install dependencies
            - name : install dependencies
              run:  |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            
            # step 4: run tests
            - name: run tests
            run: pytest